name: Build images
concurrency:
  group: ${{ github.workflow }}

on:
  push:
    branches: ["main"]
    paths:
    - 'src/WebApp'
    - '.github/workflows/build_web_image.yml'
  pull_request:
    branches: ["main"]
    paths:
    - 'src/WebApp'
    - '.github/workflows/build_web_image.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: Build and deploy to ACR
    environment: dev
    env:
      image_name: tgc-atdk-app
      app_path: src/WebApp/asgerthyregoddk
      acr_registry: tgclzdevacr.azurecr.io

    steps:
    - uses: actions/checkout@v3

    - run: |
        docker --version

    - name: 'Az CLI login'
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.ASGERTHYREGODDK_DEV_CLIENT_ID }}
        tenant-id: ${{ secrets.ASGERTHYREGODDK_DEV_TENANT_ID }}
        subscription-id: ${{ secrets.ASGERTHYREGODDK_DEV_SUBSCRIPTION_ID }}

    - run: |
        az acr login --name tgclzdevacr.azurecr.io
        cd src/TGC.HomeAutomation

        docker build . -t $acr_registry/$image_name:${{ github.sha }}
        docker build . -t $acr_registry/$image_name:latest

        docker push $acr_registry/$image_name:${{ github.sha }}
        docker push $acr_registry/$image_name:latest
      name: "Build and publish API to ACR"
      working-directory: ${{ env.app_path }}