name: Deploy Terraform

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:


permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  build_job:
    runs-on: ubuntu-latest
    environment: prd
    name: Deploy infrastructure
    defaults:
      run:
        working-directory: ./terraform
    
    env:
      ARM_CLIENT_ID: "${{ secrets.ASGERTHYREGODDK_PRD_CLIENT_ID }}"
      ARM_SUBSCRIPTION_ID: "${{ secrets.ASGERTHYREGODDK_PRD_SUBSCRIPTION_ID }}"
      ARM_TENANT_ID: "${{ secrets.ASGERTHYREGODDK_PRD_TENANT_ID }}"
      ARM_USE_AZUREAD: true

    steps:
    - uses: actions/checkout@v3

    - name: Install Terraform
      run: bash "${{ github.workspace }}/.github/scripts/install_terraform.sh" 

    - name: Terraform Fmt
      run: terraform fmt -check

    - name: Terraform Init
      run: |
        terraform init \
        -backend-config=resource_group_name="${{ secrets.ASGERTHYREGODDK_PRD_TFSTATE_RESOURCE_GROUP_NAME }}" \
        -backend-config=storage_account_name="${{ secrets.ASGERTHYREGODDK_PRD_TFSTATE_STORAGE_ACCOUNT_NAME }}" \
        -backend-config=container_name="${{ secrets.ASGERTHYREGODDK_PRD_TFSTATE_STORAGE_CONTAINER_NAME }}" \
        -backend-config=key="asgerthyregoddk.prd"
        
    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      id: plan
      run: terraform plan -input=false -var-file="envs/vars.prd.tfvars" -out=tfplan

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan